[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kooplearn"  # Required
version = "0.0.1"  # Required
description = "A package to learn Koopman operators"  # Optional
readme = "README.md" # Optional
requires-python = ">=3.7"
keywords = ["sample", "setuptools", "development"]  # Optional

authors = [
  {name = "Pietro Novelli", email = "pietronvll@gmail.com" },
  {name = "Grégoire Pacreau"},
  {name = "Bruno Belucci", email = "bruno.belucci-teixeira@dauphine.eu"},
]
dependencies = [
  "numpy",
  "scipy",
  "scikit-learn",
  "tqdm"
]

[project.optional-dependencies]
deepkoopman = [
  "torch",
  "lightning",
  "pandas",
]

visualizer = [
  "plotly",
  "dash",
  "pandas",
]

test = [
  "kooplearn[deepkoopman]",
  "kooplearn[visualizer]",
  "pytest",
]

all = [
  "kooplearn[deepkoopman]",
  "kooplearn[visualizer]",
  "kooplearn[test]",
]

#jax = [
#  "flax",
#  "ml-confs"
#]

[project.urls]  # Optional
"Homepage" = "https://github.com/CSML-IIT-UCL/kooplearn"

[tool.ruff]
line-length = 300