[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kooplearn"  
version = "0.0.1"  
description = "A package to learn Koopman operators" 
readme = "README.md"
requires-python = ">=3.7"

authors = [
  {name = "Pietro Novelli", email = "pietronvll@gmail.com" },
  {name = "Grégoire Pacreau"},
  {name = "Bruno Belucci", email = "bruno.belucci-teixeira@dauphine.eu"},
]
dependencies = [
  "numpy",
  "scipy",
  "scikit-learn",
  "tqdm"
]

[project.optional-dependencies]
deepkoopman = [
  "torch",
  "lightning",
  "pandas",
]

visualizer = [
  "plotly",
  "dash",
  "dash-mantine-components",
  "dash-iconify",
  "pandas",
]

dev = [
  "kooplearn[deepkoopman]",
  "kooplearn[visualizer]",
  "pytest",
  "sphinx",
  "sphinx-book-theme",
]

all = [
  "kooplearn[deepkoopman]",
  "kooplearn[visualizer]",
  "kooplearn[test]",
]

[project.urls]  # Optional
"Homepage" = "https://github.com/CSML-IIT-UCL/kooplearn"

[project.scripts] 
kooplearn-dashboard = "kooplearn.visualizer.dashboard:main"

[tool.ruff]
line-length = 300